export default {
  MONGO_USER_DB: process.env.MONGO_USER_DB,
  MONGO_PASSWORD_DB: process.env.MONGO_PASSWORD_DB,
  MONGO_DB_NAME: process.env.MONGO_DB_NAME,
  MONGO_HOST_DB: process.env.MONGO_HOST_DB,
  JWT_SECRET: process.env.JWT_SECRET,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET
}